### PR TITLE
Nishant

### PR DESCRIPTION
**Pull request by nishantjha161292**

### CODE REVIEW

**Comment by nishantjha161292** [comment]
1) UI/FrontEnd part of the applications are mostly designed in singleton structures. View need not be singleton but viewControllers and ViewServices are mostly composed of static/factory methods for which object is not required. (Just like in Angular JS. you don't initiate viewServices you use them.
SingleTon when into a machine derive only to meaning, either its a state or a factory. In our case its not state since we don't have any static variable being shared to other classes. Now if its a factory its can be static but in that can we don't get inheritance and thus no interface.. Its thread safe and it mostly delay performance when initially loaded after that you have instances in stack memory.

2) Classes within a package interacting - Cohesion
     Classes of different package interacting - Coupling
     Cohesion high, Coupling low. This means that interaction with UI package can be done by many to many method interactions, but when we are talking about interaction between packages their should be minimal possible access points. As for in our code GameBoard. It is the interface which provides only functions which are necessary to be accessed outside the package and rest methods are abstracted to package level.  

3) have cleaned the code, kindly run it. And let's get through the code changes if required.

4) The performance issue was introduced in yesterday nights code. Most probable reason which to me looks like is Thread.sleep(). to verify I have tried running with while loop and then with thread.sleep(). It seemed to me probable issue. We will have to optimize sleep interval I guess

**Comment by AkshayMathur92** [comment]
Comments inline relative to yours.

1. Yes, absolutely correct but in your changes the Game Service Object is singleton.  Without these changes we can parallely run multiple instances of Games but after these changes we will not be able to do that.

2. Yes correct, but in your changes concrete classes of type Input manager are tightly coupled with UI, which is wrong. BTW this problem was the same reason Input Manager was introduced yesterday, because earlier UIPlayer needed a concrete reference to UI classes which is not the case anymore. But these changes will bring that problem back.
Think about if we use some different UI class or port this code to Android, It is currenty easy since all classes are dependent on interfaces, only the implementation of UI has to be changed.
However if we accept your changes, changing the UI also means changing the UIInputManager class which is wrong. 

3. Cleanliness is well appreciated here. Wrong indentation and crappy coding should not go into master must only remain in your local branch.
Nobody will clean some one else's shit.!!
Taking some notes from your changes i have did a little revamp into SwingUI class.

4. Okay, I have also asked a beta user for review. So that might help.

**Comment by AkshayMathur92** [comment]
Also Note: 

This branch has complex conflicts. Please review before merging anything. 
To avoid such situations, please make sure you make smaller commits which does not include simultaneous changes to so many files. 

Also this code has lot of System.out.print for debugging purposes, please clean that too.

**Review by AkshayMathur92 — CHANGES_REQUESTED** [review]
Undo any changes on files out side UI package.
The package hierarchy is not correct 
, It should be the thelearninggames.chess.inputoutput
I am not sure if multiplayer would work correctly with this code, have you tested multiplayer ?
This code still requires game class to have knowledge about UI. This tight coupling has been removed in the latest master, please refer for implementation.

I would better if you only change the UI package. Rest of the changes are already present in master

**Review by AkshayMathur92 — DISMISSED** [review]
These changes are good actually much better.
Yet only few fixes required. 

1. Game should not contain any ui reference please remove it, the master branch does not have any ui reference in game class.
2. WTF is IODriver and why would you write (IODriver ioManager), this is so confusing. It should have been other way round.
3. Are you aware your changes have broken multiplayer ? 
4. Rename the package to correct hierarchy thelearninggames.chess.io
5. Remove //TODO statments and write code (CommandLineInput) 
6. Remove any System.out.println statements, 
somewhere i saw this -- System.out.println("bsdk");
7. Please do not rename classes/Interfaces. (Class names should be closed for modification), Bad coding habit. 

I would suggest that you change the package name properly and avoid modifying so many files. 
Only modify UI and IO packages.

**Pull request merged**
